import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { StandbyMark, APP_NAME } from '../components/Brand'
import { fetchSharedView, type SharePayload } from '../lib/cloud/share'
import { formatDate, formatTime } from '../lib/format'

/** Chromeless, read-only view of a shared snapshot. Opened from a share link;
    no login, no app shell. */
export function SharedView() {
  const { token } = useParams()
  const [state, setState] = useState<'loading' | 'ok' | 'missing'>('loading')
  const [data, setData] = useState<SharePayload | null>(null)

  useEffect(() => {
    let alive = true
    if (!token) {
      setState('missing')
      return
    }
    fetchSharedView(token)
      .then((d) => {
        if (!alive) return
        if (d) {
          setData(d)
          setState('ok')
        } else {
          setState('missing')
        }
      })
      .catch(() => alive && setState('missing'))
    return () => {
      alive = false
    }
  }, [token])

  return (
    <div className="shared-wrap">
      <div className="shared-card">
        <div className="shared-brand">
          <StandbyMark size={24} />
          <span>{APP_NAME}</span>
        </div>

        {state === 'loading' && <p className="muted">Loading…</p>}

        {state === 'missing' && (
          <>
            <h1>Link unavailable</h1>
            <p className="muted">
              This view-only link is invalid or has been revoked. Ask your stage manager for a fresh one.
            </p>
          </>
        )}

        {state === 'ok' && data && (
          <>
            <p className="shared-kicker">View-only{data.company ? ` · ${data.company}` : ''}</p>
            <h1>{data.title}</h1>

            {data.schedule && data.schedule.length > 0 && (
              <section>
                <h2>Schedule</h2>
                {data.schedule.map((e, i) => (
                  <div key={i} className="shared-ev">
                    <div className="shared-ev-head">
                      <strong>{e.title || e.type}</strong>
                      <span className="muted small">
                        {formatDate(e.date)}
                        {e.callTime ? ` · Call ${formatTime(e.callTime)}` : ''}
                        {e.startTime ? ` · ${formatTime(e.startTime)}` : ''}
                        {e.endTime ? `–${formatTime(e.endTime)}` : ''}
                        {e.location ? ` · ${e.location}` : ''}
                      </span>
                    </div>
                    {e.agenda && e.agenda.length > 0 && (
                      <div className="shared-agenda">
                        {e.agenda.map((a, j) => (
                          <div key={j} className="row" style={{ gap: 10, alignItems: 'baseline' }}>
                            <span className="shared-time">{a.time ? formatTime(a.time) : '—'}</span>
                            <span className="small">{a.what}</span>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                ))}
              </section>
            )}

            {data.companyList && data.companyList.length > 0 && (
              <section>
                <h2>Company</h2>
                {data.companyList.map((p, i) => (
                  <div key={i} className="row-between shared-person">
                    <span>
                      <strong>{p.name}</strong>
                      {p.character ? <span className="muted"> — {p.character}</span> : null}
                    </span>
                    <span className="muted small">{p.role}</span>
                  </div>
                ))}
              </section>
            )}

            <p className="shared-foot">
              Read-only · generated by {APP_NAME}. <Link to="/">Open {APP_NAME}</Link>
            </p>
          </>
        )}
      </div>
    </div>
  )
}
